### PR TITLE
src folder now takes sources relative to CMAKE_CURRENT_LIST_DIR

### PR DESCRIPTION
**Pull request by OmniSudo**
I could never get daxa to be included as a subproject so I fixed it.

### CODE REVIEW

**Comment by GabeRundlett** [comment]
This should not ever be necessary

**Comment by OmniSudo** [comment]
It is when src isn't at the root level of a CMakeLists.txt chain

**Comment by GabeRundlett** [comment]
what do you mean "CMakeLists.txt chain"? Are you using `add_subdirectory()`? or `include()`?

**Comment by OmniSudo** [comment]
I have my top level CML.txt @ ~/Workspace/SkillQuest/CML.txt and daxa is in ~/Workspace/SkillQuest/ipotrick/daxa/CML.txt

**Comment by OmniSudo** [comment]
Okay, add_subdirectory works, this can be closed

**Pull request closed without merging**
