### PR TITLE
Atomic float op + slang RT compilation

### PR DESCRIPTION
**Pull request by Jaisiero**
- Optional atomic float op.
- Slang RT minimum code to compile with RAY TRACING flag (not supported yet).

### CODE REVIEW

**Comment by Ipotrick** [comment]
I merge after the prefix is added

**Comment by GabeRundlett** [comment]
Note, as device.h and device.cpp just had a different feature made optional, in master the device flag 1 << 11 is already used.

**Comment by Jaisiero** [comment]
What do you mean by prefix? the flags were fixed

**Comment by Ipotrick** [comment]
I was tired reading this there is nothing wrong with what you did

**Pull request merged**
