### PR TITLE
Fixing shader group count bug

### PR DESCRIPTION
**Pull request by Jaisiero**
-> Bug fixed and minor change to allow more group shaders in the SBT. 
I don't know if those should be possible to make them variable size. Daxa C interface doesn't provide any example of this. List all are fixed size I image because this is for a reason.

### CODE REVIEW

**Comment by Jaisiero** [comment]
1. Merge with master.
2. Fixed some bug when hit shaders overcome shader groups.
3. Added Shader Execution Reorder (SER) support on RT pipeline.
4. Added SBT handle offsets support.

**Comment by Ipotrick** [comment]
looks good to me @GabeRundlett can you take a look here?

**Comment by Ipotrick** [comment]
If you want them to be variable size you just pass a pointer and count to the info.

**Comment by GabeRundlett** [comment]
The reason that there's no variable list size is because you're able to retrieve this info, as it's stored internally. This means that it'd need to be copied in the case of a variable size, which I think is okay. We just haven't done this anywhere I think. I will see if I can add that into master for you.

**Comment by GabeRundlett** [comment]
Added new Span type with 73359c3df2d73aeccbe68de108d9e81f3249f888

**Pull request merged**
