### PR TITLE
adding option to clamp to border and border being white

### PR DESCRIPTION
**Pull request by lukasino1214**

### CODE REVIEW

**Comment by GabeRundlett** [comment]
I need to see how to not have package updates not trigger on PR check

**Comment by lukasino1214** [comment]
Yeah I just noticed. This should fix my shadows

**Comment by GabeRundlett** [comment]
We should not modify the default "null" sampler to be white. If you need a clamp to border, white colored sampler, you should create one. So we need to add the clamp to border address mode, and a new property, the border color.

**Comment by lukasino1214** [comment]
Good point. It should be fixed

**Comment by Ipotrick** [comment]
Two things need to be changed.
Default sampler should be transparent black and so should be the default option in create info

**Pull request merged**
