### PR TITLE
Fixed spelling mistakes and linked learndaxa.com in the README

### PR DESCRIPTION
**Pull request by FabulousCodingFox**
- Fixed a lot of missing hyphons
- Removed the old outdated wiki & tutorial
- Linked Learndaxa.com as the new wiki & tutorial
- Fixed wrong markdown heading type

### CODE REVIEW

**Comment by GabeRundlett** [comment]
"Generous clean-up of code"

**Comment by Ipotrick** [comment]
Why did you delete the book files?
Its not outdated its just incomplete.

**Comment by GabeRundlett** [comment]
Presumably as it is being ported into the website instead. Why host the mdbook if that's what LearnDaxa is
LearnDaxa is just MD

**Comment by Ipotrick** [comment]
Is the content already copied over to LearnDaxa?

**Comment by GabeRundlett** [comment]
It actually might be, FabFox is checking real quick. https://wiki.learndaxa.com/
modifiable here: https://github.com/learndaxa/Wiki

**Pull request closed without merging**
